# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_w_r <- function(num_genes, num_studies, r) {
    .Call('_BiGER_init_w_r', PACKAGE = 'BiGER', num_genes, num_studies, r)
}

cpp_BiGER <- function(r, n_r, n_u, W, mu, sigma2, alpha = 1.0, beta = 1.0, save_chains = FALSE, save_burnin = FALSE, iter = 20000L, burnin = 10000L, verbose = -1L) {
    .Call('_BiGER_cpp_BiGER', PACKAGE = 'BiGER', r, n_r, n_u, W, mu, sigma2, alpha, beta, save_chains, save_burnin, iter, burnin, verbose)
}

cpp_bBiGER <- function(r, n_r, n_u, mu, sigma2, alpha = 1.0, beta = 1.0, method_bound = "normal", save_chains = FALSE, save_burnin = FALSE, iter = 5000L, burnin = 2500L, verbose = -1L) {
    .Call('_BiGER_cpp_bBiGER', PACKAGE = 'BiGER', r, n_r, n_u, mu, sigma2, alpha, beta, method_bound, save_chains, save_burnin, iter, burnin, verbose)
}

cpp_vBiGER <- function(r, n_r, n_u, mu, sigma2_inv, alpha = 1.0, beta = 1.0, method_bound = "normal", max_iter = 100L, delta = 0.0001, verbose = -1L) {
    .Call('_BiGER_cpp_vBiGER', PACKAGE = 'BiGER', r, n_r, n_u, mu, sigma2_inv, alpha, beta, method_bound, max_iter, delta, verbose)
}

